"""Port protocols (§4, PA-1): the engine's ports-and-adapters seam.

Structural (duck-typed) contracts -- adapters need not inherit from these,
only implement matching methods. See `docs/ports/<port>.md` for each port's
written contract (error semantics, idempotency expectations); a contract
change here applies to every adapter of that port (PA-1). Concrete adapters
are resolved from config via `engine.registry.build_adapter`, never
imported directly by task-running code.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Protocol

from engine.models import Event, GateDecision, GateRequest, TaskRun, TicketDetails


class Tracker(Protocol):
    """§4 `tracker`. Canonical (P0): `github-issues`."""

    def fetch_ticket(self, ref: str) -> TicketDetails: ...
    def parse_event(self, payload: dict, event_key: str) -> Event | None: ...
    def set_status_labels(self, ticket_id: str, status: str, labels: list[str]) -> None: ...
    def upsert_pinned_comment(self, ticket_id: str, body: str, event_id: str) -> str | int: ...
    def post_closing_summary(self, ticket_id: str, body: str, event_id: str) -> None: ...
    def healthcheck(self) -> bool: ...


class Executor(Protocol):
    """§4 `executor`. Canonical (P0): `claude-code-headless`."""

    def start(self, run_ctx: TaskRun) -> None: ...
    def result(self, run_ctx: TaskRun) -> dict | None: ...
    def healthcheck(self) -> bool: ...


class AgentSession(Protocol):
    """§4 `agent-session`. Canonical (P0): `claude-code-headless`."""

    def prepare_worktree(self, run_id: str, repo: str, base_commit: str | None) -> Path: ...
    def run(self, bundle: dict, tools: list[str], deadline: str) -> dict: ...
    def collect_outputs(self, worktree: Path, declared: list[str]) -> list[str]: ...
    def build_pr_branch(self, run_id: str, worktree: Path, base_commit: str | None) -> str: ...
    def open_draft_pr(self, repo: str, branch: str, base: str, title: str, body: str) -> str: ...
    def mark_pr_ready(self, pr_ref: str) -> None: ...
    def request_reviewers(self, pr_ref: str, members: list[str]) -> None: ...
    def healthcheck(self) -> bool: ...


class Messaging(Protocol):
    """§4 `messaging`. Canonical (P0): `github-comment`."""

    def notify(self, audience: dict, message: str, links: list[str], event_id: str) -> None: ...
    def healthcheck(self) -> bool: ...


class Poll(Protocol):
    """§4 `poll`. Protocol only in P0 (D3) -- no adapter ships before P1."""

    def open(self, question: str, options: list[str], audience: str) -> str: ...
    def tally(self, poll_ref: str) -> dict: ...
    def resolve(self, poll_ref: str, quorum: int) -> dict: ...
    def healthcheck(self) -> bool: ...


class Gate(Protocol):
    """§4 `gate`. Canonical (P0): `pr-review`."""

    def request(self, group: str, subject: dict) -> GateRequest: ...
    def status(self, run: dict) -> GateDecision: ...
    def healthcheck(self) -> bool: ...


class QaEnv(Protocol):
    """§4 `qa-env`. Protocol only in P0 (D3) -- no adapter ships before P1."""

    def up(self, repos: list[str], fixtures: dict) -> str: ...
    def down(self) -> None: ...
    def capture(self, dest: str) -> None: ...
    def healthcheck(self) -> bool: ...


class StateStore(Protocol):
    """Not a §4 port (PD-7) -- documents `engine.state.GitJsonStateStore`'s
    shape for callers that type against it. Fixed single implementation;
    never resolved through `engine.registry.build_adapter`.
    """

    def read_state(self, ticket_id: str) -> dict | None: ...
    def write(self, fn: Callable[..., None]) -> None: ...
    def claim_run(
        self, ticket_id: str, run_id: str, now_iso: str, max_runtime_min: float
    ) -> bool: ...
    def healthcheck(self) -> bool: ...
